Add ESLint and GitHub Actions for client
ptr-geeks/ptrun pull request #7
Opened 2021-08-17 14:28 UTC by filips123

2021-08-17 16:24 UTC, filips123 commented
I think PR is ready now.

2021-08-18 17:03 UTC, davidmohar requested changes
I think we can remove `client/src/index.js` & `client/src/objects/terrain.js` from this PR as it's out of scope for this change. Those should be fixed separately after this gets merged to `develop`.

2021-08-18 17:03 UTC, davidmohar commented on .github/workflows/client.yaml
> +      - name: Upload artifacts
I think we don't need to upload artifacts at this stage. This should be done during release from `master` and for now only as a Docker image.

2021-08-18 17:03 UTC, davidmohar commented on .github/workflows/client.yaml
> +  docker:
This action should only run when we release from `master` (ie. create a tag)

2021-08-18 17:03 UTC, davidmohar commented on .github/workflows/client.yaml
> +          tags: type=ref,event=branch
Probably better to use `type=ref,event=tag` since we will only build these when doing a release

2021-08-18 17:03 UTC, davidmohar commented on .github/workflows/client.yaml
> +          flavor: latest=${{ github.ref == 'refs/heads/master' }}
This should be `true` every time

2021-08-19 08:00 UTC, davidmohar approved these changes

2021-08-19 08:00 UTC, merged