Added GitHub CI for Go
ptr-geeks/ptrun pull request #9
Opened 2021-08-17 15:35 UTC by mytja

This file now builds Go file & Docker file... You can see example run here: https://github.com/mytja-archive/ptrun/actions/runs/1139865571

I don't know how to integrate tests, so for now I won't integrate them...

I made a lot of commits, so I recommend you to squash them in a single commit...

2021-08-17 16:03 UTC, mytja commented
Done. Everything is optimized...

2021-08-18 16:57 UTC, davidmohar requested changes
`server/tests/server_test.go` should be removed from this PR as it's not relevant to the overall story of this request. Otherwise everything else looks good and only needs minor improvements before we merge.

2021-08-18 16:57 UTC, davidmohar commented on .github/workflows/server.yaml
> +  docker:
Can we make this run only on `develop` & `master` branches as a manual action so we don't push images to ghcr every time someone makes a PR and/or change there.

2021-08-18 16:57 UTC, davidmohar commented on .github/workflows/server.yaml
> +          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
We should be using `>=1.15`

2021-08-19 07:03 UTC, mytja commented
This has been fixed

2021-08-19 07:58 UTC, mytja commented
https://github.com/mytja-archive/ptrun/actions/runs/1146131878

2021-08-19 08:21 UTC, mytja commented
Everything is done
https://github.com/mytja-archive/ptrun/actions/runs/1146202183

2021-08-19 08:35 UTC, davidmohar approved these changes

2021-08-19 08:36 UTC, merged